//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yagisotomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yagislar
    {
        public int YagisId { get; set; }
        public Nullable<int> IlId { get; set; }
        public Nullable<int> Yil { get; set; }
        public string Ay { get; set; }
        public Nullable<double> Miktar { get; set; }
    
        public virtual Iller Iller { get; set; }
    }
}
